version: '3'
services:
  microservices_go:
    image: golang:1.15
    working_dir: /go/src/goApp
    expose:
      - 8080    
    labels:
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.docker.network=revand_network"
    restart: on-failure
    networks:
      - revand_network
    command: >
      bash -c " rm -f go.mod || true &&
      rm -f go.sum || true &&
      go mod init goApp &&
      go mod tidy &&
      go get github.com/pilu/fresh &&
      fresh"