version: '3'
services:
  laravel:
    build: ./backend/laravel
    ports:
    - "8000:8000"
    networks:
    - revand_network
    links:
    - mysql
    - go
    depends_on:
    - mysql
    - go
  go:
    build: ./backend/go
    ports:
    - "3000:3000"
    networks:
    - revand_network
    links:
    - mysql
    depends_on:
    - mysql
  angular:
    build: ./frontend/angular
    ports:
    - "4200:4200"
    networks:
    - revand_network
    links:
    - go
    - laravel
    depends_on:
    - go
    - laravel
  mysql:
    image: mysql:5.7
    ports:
    - "3306:3306"
    networks:
    - revand_network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: revand
      MYSQL_USER: vicnx
      MYSQL_PASSWORD: 12345678
networks:
    revand_network: