version: '3'
services:
  laravel:
    container_name: revand_laravel
    build: ./backend/laravel
    working_dir: /app
    volumes:
    - ./backend/laravel:/app
    ports:
    - "8000:8000"
    networks:
    - revand_network
    restart: on-failure
    depends_on:
    - mysql
    - redis
    - users
    - mongo
    working_dir: /app
    command: >
      bash -c " composer install &&
      composer update laravel/framework &&
      cp .env.example .env &&
      php artisan key:generate &&
      php artisan route:list &&
      php artisan migrate &&
      php artisan migrate:refresh &&
      php artisan serve --host=0.0.0.0 --port=8000"
      
  users:
    container_name: revand_go_users
    image: golang:1.15
    working_dir: /go/src/goApp
    volumes:
      - ./backend/go3/users:/go/src/goApp
    restart: on-failure
    labels:
      # - "traefik.enable=true"
      - "traefik.http.routers.users.rule=Host(`users.docker.localhost`)"
      # - "traefik.http.routers.users.rule=Host(`users.local`) && PathPrefix(`/`)"
      # - traefik.frontend.rule=Host:localhost;PathPrefix:/api


      # - "traefik.backend=users"
      # - "traefik.frontend.rule=Path: /users"
      # - "traefik.port=3000"
      # - "traefik.docker.network=revand_network"


      # - traefik.frontend.rule=Host:users.docker.localhost
      # - traefik.docker.network=revand_network
      # - traefik.site.port=6969
    networks:
    - revand_network
    # CGO_ENABLED=0 go build -installsuffix 'static' -o /users . 
    command: >
      bash -c "
      && rm -f go.mod || true
      && rm -f go.sum || true
      && go mod init goApp
      && go mod tidy
      && go get github.com/pilu/fresh
      && fresh "

  angular:
    container_name: revand_angular
    build: ./frontend/angular
    working_dir: /app
    volumes:
    - ./frontend/angular:/app
    ports:
    - "4200:4200"
    networks:
    - revand_network
    restart: on-failure
    depends_on:
    - users
    - laravel
    working_dir: /app
    command: bash -c "npm install && npm start"
  mysql:
    container_name: revand_mysql
    image: mysql:5.7
    ports:
    - "3306:3306"
    networks:
    - revand_network
    restart: on-failure
    volumes:
    - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: revand
      MYSQL_USER: vicnx
      MYSQL_PASSWORD: 12345678
  mongo:
    container_name: revand_mongo
    image: mongo:3.5
    ports:
      - "27017:27017"
    volumes:
      - "mongodata:/data/db"
    restart: on-failure
    # environment:
      # MONGODB_USER: jowi
      # MONGODB_PASS: 12345678
      # MONGODB_DATABASE: revand

      # MONGO_INITDB_ROOT_USERNAME: jowi
      # MONGO_INITDB_ROOT_PASSWORD: 12345678
      # MONGO_INITDB_DATABASE: revand
    networks:
      - revand_network
    # command: mongod
  redis:
    image: redis:alpine
    container_name: revand_redis
    restart: on-failure
    ports: 
      - "6379:6379"
    volumes:
      - "redis:/redis_data"
    networks: 
      - revand_network
  traefik:
    # The official v2 Traefik docker image
    image: traefik:v2.3
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.dashboard=true --api.insecure=true --providers.docker --entrypoints.web.address=:80
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - users
  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"
  grafana:
    image: grafana/grafana:7.1.5
    container_name: revand_grafana
    ports:
    - "3500:3000"
    restart: on-failure
    volumes:
    - './common/grafana:/etc/grafana/provisioning/datasources/'
    - 'myGrafanaVol:/var/lib/grafana'
    networks:
    - revand_network
    depends_on: 
    - users
    - laravel
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_INSTALL_PLUGINS: "grafana-clock-panel 1.0.1"
networks:
    revand_network:
volumes:
    db_data:
    myGrafanaVol:
    redis:
    mongodata:
    # mongodb: