# global:
#   scrape_interval: 5s
#   evaluation_interval: 30s
# scrape_configs:
#   - job_name: "revand"
#     honor_labels: true
#     static_configs:
#       - targets: ["go_products.docker.localhost"]

global:
  scrape_interval:     15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: revand
    static_configs:
    - targets: ['traefik:8080']
